# Generated by Django 4.1.5 on 2023-01-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_remove_favpoke_pokeuser_favpoke_pokeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favpoke',
            name='pokeUser',
            field=models.ManyToManyField(related_name='pokeUser', to='pokemon.pokemon'),
        ),
    ]
